### ISSUE TITLE
Goal of parameter default value

### ISSUE THREAD

**Issue by femtotrader** [SmokinCaterpillar/pypet#34]
Hello,

After seeing PyData video https://www.youtube.com/watch?v=a8Qq8kPS-dg I'm having a look at pypet.

I'd like to build something quite similar (probably much simpler, with less features) in Julia with [JLD](https://github.com/JuliaIO/JLD.jl) as backend.

So I first had a look at
https://pypet.readthedocs.io/en/latest/examplesdoc/example_01.html

You did

```python
# Add both parameters
traj.f_add_parameter('x', 1, comment='I am the first dimension!')
traj.f_add_parameter('y', 1, comment='I am the second dimension!')
```

I don't understand what is the purpose of parameter default value

If I don't set default value it raises

    TypeError: Your parameter `parameters.x` has no default value, please specify one via `f_set` before exploration.

but from my understanding, we shouldn't have to do this because

```python
In [10]: cartesian_product({'x':[1,2,3,4], 'y':[6,7,8]})
Out[10]:
{'x': [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
 'y': [6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8]}
```

so (from my understanding) default value for `x` should be `1` and default value for `y`should be `6` when no default value is given.

I also why we are building this in-memory dict and not working with iterator ?
Because this big amount of parameter and big number of value for each parameter it can be very memory costly.

Sorry for my newbie question.

Kind regards

**Comment by SmokinCaterpillar** [comment]
Hi,

you need to specify a default value in order to set the type of parameter at hand.
`traj.f_add_parameter('x', 1, comment='I am the first dimension!')`
will give you an integer parameter. From that moment in time on it is clear that the parameter can only take integer values. Moreover, at the time of parameter specification it is not necessarily decided which parameters you do explore later on. So all parameters should have a default value such that the model can be run without exploring any parameter explicitly. The assumption of *pypet* is that you usually have highly parametrized systems with several hundreds of parameters, but only a minority is actually explored. Hence, for most parameters you do use the default value. In the simple online example there are only two parameters, but if you look at this more realistic [example](http://pypet.readthedocs.io/en/latest/examplesdoc/example_24.html), you'll see that most of the parameters are kept with their default values.


I had the idea to work with iterators or actually generators (the former still needs all the memory) for explored parameters. However, to my mind there were more limitations to this approach than advantages.

Well, using generators could potentially be advantageous because you do not need all data in memory. However, this makes slicing and searching for particular parameter combinations less efficient. If I was looking for a specific run, for instance one where $x=4$ and $y=10$, and if I was using a generator, I would need to load all data sequentially until I stumble upon the particular parameter combination eventually. In memory python allows me to search with O(1) [on average] instead of O(N). Alternatively, my generator must implement a thorough DataBase query mechanic in order to find the particular run in O(log N) instead of O(N). O(log N) is IMO the best you can do in an indexed database (until quantum computing becomes a thing, of course^^). So the generators approach is a bit over the top. Indeed, the assumption here is that the explored parameter data is small in comparison to the obtained results, so it can be loaded into memory at once without any problems.

Cheers,
Robert

**Comment by femtotrader** [comment]
Thanks a lot for your very kind and informative answer.
