### ISSUE TITLE
simplify method interface

### ISSUE THREAD

**Issue by lsolanka** [SmokinCaterpillar/pypet#5]
I have noticed that many methods/attributes, e.g. for the Trajectory class, have a prefix like f_ and v_. Wouldn't it be more readable for the user if these prefixes are removed? They seem quite redundant, since simply having a look into the documentation makes it clear what is a class method and attribute.

**Comment by SmokinCaterpillar** [comment]
Btw, the new version supports an interface that goes into this direction:
Instead of `myobj.f_my_func()` you can alternatively use `myobj.func.my_func()`.
This applies to variables, properties, and attributes as well: ``myobj.v_comment`` can also be accessed via ``myobj.vars.comment``. This features makes it easier for you if you use an interactive shell like ipython and hit tab for auotcompletion: ``myobj.func. + TAB`` will only list all functions. Btw ``myobj.kids. + TAB`` will only list all user data.
